config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users

  root 'library#index'
  resources :books do
    resources :collections, only: [:edit, :update, :destroy], module: "books"
    resource :merge, only: [:show, :new, :create]
  end

  resources :library, only: :index
  resources :logs, only: :index
  resources :halted_files, only: :destroy
  resources :documents, only: :show do
    get :download, on: :member
    post :convert, on: :member
    post :split, on: :member
    post :kindle, on: :member
  end
  resources :collections, only: [:index, :new, :create]
  resources :epubs, only: :show

  mount API::API => '/'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :books, -> { select(:id, :name).order(:created_at) }

  validates :name, presence: true
end

app/controllers/books/collections_controller.rb
module Books
  class CollectionsController < ApplicationController
    before_action :authenticate_user!

    def edit
      authorize Collection

      @book = Book.find(params[:book_id])
      @collections = current_user.collections.order(:name)
    end

    def update
      authorize Collection

      @book = Book.find(params[:book_id])
      @book.update(collection_ids: permitted_collection_ids)
    end

    private

    def permitted_collection_ids
      collection_ids = params
        .require(:book)
        .permit(collection_ids: [])
        .fetch(:collection_ids, [])
        .map(&:to_i)

      current_user.collection_ids & collection_ids
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @collections = current_user.collections.includes(:books).order(:name)
  end

  def new
    @collection = current_user.collections.new
    authorize @collection
  end

  def create
    @collection = current_user.collections.new(collection_params)
    if @collection.save
      redirect_to collections_path, notice: "Collection was successfully created."
    else
      render :new
    end
  end

  private

    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/views/collections/_collection.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h5 class="card-title">
          <%= collection.name %>
        </h5>
        <ul class="list-group list-group-flush">
          <% if collection.books.any? %>
            <% collection.books.each do |book| %>
              <li class="list-group-item bg-dark">
                <%= link_to(book.name, book_path(book), class: "text-white") %>
              </li>
            <% end %>
          <% else %>
            <li class="list-group-item bg-dark">No books here.</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h4 class="card-title mr-auto d-inline-block mb-0">
          <%= pluralize(@collections.flat_map(&:books).size, "book") %>
          across
          <%= pluralize(@collections.size, "collection") %>
        </h4>
        <span class="float-right">
          <%= link_to new_collection_path, class: "text-white" do %>
            <%= octicon(:plus, height: 24, fill: "currentcolor") %>
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

<%= render @collections %>

app/views/collections/new.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h5 class="card-title">
          Create Collection
        </h5>
        <%= form_with(model: @collection, local: true) do |form| %>
          <% if @collection.errors.any? %>
            <div class="alert alert-danger">
              <p><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</p>

              <ul>
              <% @collection.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.submit class: "btn btn-secondary float-right" %>
          </div>
        <% end %>
      </div>
      <div class="card-footer">
        <%= link_to 'Back', collections_path, class: "text-white" %>
      </div>
    </div>
  </div>
</div>