config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users

  root 'library#index'
  resources :books do
    resources :collections, only: [:edit, :update, :destroy], module: "books"
    resource :merge, only: [:show, :new, :create]
  end

  resources :library, only: :index
  resources :logs, only: :index
  resources :halted_files, only: :destroy
  resources :documents, only: :show do
    get :download, on: :member
    post :convert, on: :member
    post :split, on: :member
    post :kindle, on: :member
  end
  resources :collections, only: [:index, :new, :create]
  resources :epubs, only: :show

  mount API::API => '/'
end

app/controllers/merges_controller.rb
class MergesController < ApplicationController
  before_action :authenticate_user!

  def new
    authorize book
  end

  def create
    authorize book

    book.merge!(Book.find(params[:duplicate_book_id]))

    redirect_to book_path(book), notice: "Books merged"
  end

  def show
    books = Book.select(:id, :name)
      .where.not(id: params[:book_id])
      .search(params[:term])
      .limit(10)

    respond_to do |format|
      format.json { render json: { results: books.map { |b| { id: b.id, text: b.name } } } }
    end
  end

  private

  def book
    @book ||= Book.find(params[:book_id])
  end
end

app/views/merges/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-10">
    <div class="card text-white bg-dark">
      <div class="card-body">
        <%= form_with(url: book_merge_path(@book), method: :post) do |f| %>
          <div class="form-group">
            <%= f.label :duplicate_book_id, "Select duplicated book" %>

            <%= f.select :duplicate_book_id, [], {}, { class: "form-control ac-select2", data: { url: book_merge_path(@book) }} %>
          </div>

        <div class="form-group">
            <%= f.submit class: "btn btn-secondary float-right" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>