config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users

  root 'library#index'
  resources :books do
    resources :collections, only: [:edit, :update, :destroy], module: "books"
    resource :merge, only: [:show, :new, :create]
  end

  resources :library, only: :index
  resources :logs, only: :index
  resources :halted_files, only: :destroy
  resources :documents, only: :show do
    get :download, on: :member
    post :convert, on: :member
    post :split, on: :member
    post :kindle, on: :member
  end
  resources :collections, only: [:index, :new, :create]
  resources :epubs, only: :show

  mount API::API => '/'
end

app/models/story.rb
class Story < ApplicationRecord
  include PgSearch::Model

  has_one_attached :favicon
  has_one_attached :picture

  pg_search_scope :search, against: [
      [:title, 'A'],
      [:tags, 'A'],
      [:description, 'B'],
      [:domain, 'C'],
    ],
    using: {
      tsearch: {
        prefix: true,
        dictionary: 'english',
        tsvector_column: 'searchable'
      }
    }

  scope :with_tag, ->(tag) {
    where('? = ANY(tags)', tag)
  }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  def index
    @stories = Story.all
      .with_attached_picture
      .with_attached_favicon

    @stories = @stories.with_tag(params[:tag]) if params[:tag].present?
    @stories = @stories.search(params[:q]) if params[:q].present?
    @stories = @stories.order(updated_at: :desc) unless @stories.order_values.any?
    @stories = @stories.page(params[:page]).per(26)

    @stories = Decorators::Story::Index.pagination_wrap(@stories)
  end

  def show
    @story = Decorators::Story::Show.new(@story)
  end

  def new
    @story = Story.new(url: params[:url])
  end

  def edit
  end

  def create
    @story = StoryUrl.new(create_params)

    if @story.save
      redirect_to stories_url, notice: 'Story was successfully enqueued for creation'
    else
      render :new
    end
  end

  def update
    if @story.update(update_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private

    def set_story
      @story = Story.find(params[:id])
    end

    def create_params
      params.require(:story).permit(:url).merge(user: current_user)
    end

    def update_params
      params.require(:story).permit(:title, :description, tags: []).tap do |prms|
        prms[:tags].select!(&:present?)
      end
    end
end

app/views/stories/_form.html.erb
<%= bootstrap_form_with(model: story, local: true) do |form| %>
  <% if story.persisted? %>
    <%= form.text_field :title %>
    <%= form.text_area :description %>
    <%= form.select :tags, story.tags, {}, { class: "form-control select2-tags-input", multiple: true } %>

  <% else %>
    <%= form.text_field :url %>
  <% end %>

  <%= form.submit class: "btn btn-secondary float-right" %>
<% end %>

app/views/stories/_new_story.html.erb
<%= render('form', story: @story) %>

<div class="form-group mt-5">
  <p>Or send it in an email to your custom address:</p>
  <%= text_field_tag(:email, current_user.subscription_email, class: "form-control") %>
  <p>Please keep this address private, because anyone can submit stories as you with it.</p>
</div>

app/views/stories/_story.html.erb
<div class="card text-white bg-dark">
  <div class="card-body">
    <div class="d-flex flex-row justify-content-center">
      <div class="flex-grow-1">
        <h5 class="card-title text-wrap text-break"><%= story.title_link %></h5>
        <div class="card-subtitle">
          <div class="d-flex align-items-center">
            <% if story.favicon.attached? %>
              <div class="og-favicon" style="background-image: url('<%= url_for(story.favicon) %>');"></div>
            <% end %>
            <div class="text-wrap text-break"><%= story.domain %></div>
          </div>
        </div>
        <p class="card-text small text-wrap text-break" title="<%= story.description %>" ><%= story.summarization %></p>
      </div>

      <% if story.picture.attached? %>
        <div class="flex-shrink-0 mr-2">
          <div style="width: 80px; height: 100%; background-size: contain; background-repeat: no-repeat; background-image: url('<%= url_for(story.thumbnail) %>');"></div>
        </div>
      <% end %>

      <div>
        <div class="row mb-2">
          <%= link_to octicon("eye", fill: "currentcolor"),
                story_path(story), class: "ml-3 btn btn-secondary" %>
        </div>
        <div class="row">
          <%= link_to octicon("pencil", fill: "currentcolor"),
                edit_story_path(story), class: "ml-3 btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="d-flex flex-row justify-content-center">
      <div class="flex-grow-1">
        <%= story.tag_badges %>
      </div>
      <dir class="card-text small flex-shrink-0 text-wrap text-break">
        Updated <%= story.last_updated_at %> ago
      </dir>
    </div>
  </div>
</div>

app/views/stories/edit.html.erb
<%= with_card 'Editing Story', render('form', story: @story), link_to('Back', stories_path, class: "text-white") %>

app/views/stories/index.html.erb
<div class="row justify-content-center">
  <div class="col-8">
      <%= form_with url: stories_path, method: :get, local: true do |f| %>
       <div class="form-group mt-3">
        <%= f.search_field :q, value: params[:q], class: "form-control form-control-lg", placeholder: "Search", autofocus: autofocus_search_input?, aria: { label: "Search" } %>
        <%= f.submit "Search", class: "d-none" %>
        </div>
      <% end %>
  </div>
</div>

<% if @stories.any? %>
  <% @stories.each_slice(2) do |stories| %>
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="card-deck mt-3">
          <%= render partial: "story", collection: stories, as: :story %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= paginate @stories %>
    </div>
  </div>
<% else %>
  <div class="row justify-content-center">
    <div class="col-10">
      <p class="placeholder">There are no stories yet. But you can <%= link_to 'add', new_story_path %> a new one</p>
    </div>
  </div>
<% end %>

app/views/stories/new.html.erb
<%= with_card(
    'New Story',
    render('new_story'),
    link_to('Back', stories_path, class: "text-white")
  )
%>

app/views/stories/show.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="mt-3">
      <div class="card text-white bg-dark">
        <div class="card-body">
          <h5 class="card-title">
            <span>
              <%= @story.title %>
            </span>
            <span class="float-right">
              <%= link_to octicon("pencil", fill: "currentcolor"),
                  edit_story_path(@story), class: "ml-3 btn btn-secondary" %>
            </span>
          </h5>

          <div class="card-subtitle">
            <div class="d-flex align-items-center">
              <div class="og-favicon" style="background-image: url('<%= url_for(@story.favicon) %>');"></div>
              <div class="text-wrap text-break"><%= @story.title_link %></div>
            </div>
          </div>
          <h6 class="card-subtitle mt-2">

          </h6>
          <p class="card-text small"><%= @story.summarization %></p>
        </div>
        <div class="card-footer">
          <%= @story.tag_badges %>
        </div>
      </div>
    </div>
  </div>
</div>