config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users

  root 'library#index'
  resources :books do
    resources :collections, only: [:edit, :update, :destroy], module: "books"
    resource :merge, only: [:show, :new, :create]
  end

  resources :library, only: :index
  resources :logs, only: :index
  resources :halted_files, only: :destroy
  resources :documents, only: :show do
    get :download, on: :member
    post :convert, on: :member
    post :split, on: :member
    post :kindle, on: :member
  end
  resources :collections, only: [:index, :new, :create]
  resources :epubs, only: :show

  mount API::API => '/'
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize ImportLog

    @logs = ImportLog.order(created_at: :desc)
    @logs = @logs.with_error if params.key?(:error)
    @logs = @logs.halted if params.key?(:halted)
    @logs = @logs.page(params[:page]).per(50)
  end
end

app/views/logs/_log.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mb-2">
      <div class="card-header" id="heading-<%= log.id %>">
        <h5 class="mb-0">
          <button class="btn btn-link text-white" data-toggle="collapse" data-target="#collapse-<%= log.id %>" aria-expanded="false" aria-controls="collapse-<%= log.id %>">
            <span>#<%= log.id %>.</span>
            <%= log.created_at %>
            <%= octicon("alert", class: "ml-2", fill: "currentcolor") if log.fail? %>
            <%= octicon("stop", class: "ml-2", fill: "currentcolor") if log.halted? %>
          </button>
        </h5>
      </div>

      <div id="collapse-<%= log.id %>" class="collapse" aria-labelledby="heading-<%= log.id %>" data-parent="#accordion">
        <div class="card-body">
          <pre class="text-white"><%= JSON.pretty_generate(log.data) %></pre>
        </div>
        <div class="card-footer">
          <%= content_tag(:div, id: "halted-button-#{log.id}") do %>
            <% if policy(log).destroy? && log.halted? && log.has_file? %>
              <%= link_to octicon("x", fill: "currentcolor"), halted_file_path(log), method: :delete, data: { confirm: "Are you sure?" }, title: "Remove file", remote: true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/logs/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-10">
    <nav>
      <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
        <%= link_to "All", logs_path, class: "nav-item nav-link #{'active' if params.slice(:error, :halted).empty?}", role: "tab", aria: { selected: params.empty? } %>
        <%= link_to "Errors", logs_path(error: ""), class: "nav-item nav-link #{'active' if params.key?(:error)}", role: "tab", aria: { selected: params.key?(:error) } %>
        <%= link_to "Halted", logs_path(halted: ""), class: "nav-item nav-link #{'active' if params.key?(:halted)}", role: "tab", aria: { selected: params.key?(:halted) } %>
      </div>
    </nav>
  </div>
</div>

<div id="accordion" class="mt-3">
  <%= render partial: "log", collection: @logs, as: :log %>
</div>

<div class="row justify-content-center">
  <div class="col-10">
    <%= paginate @logs %>
  </div>
</div>